### ISSUE TITLE
Некоторые рандом изменения законов для ИИ надо переделать

### ISSUE THREAD

**Issue by Kapitolina** [Rampoch/Chaotic-Onyx#33]
ADMIN LOG: EVENT has given Ghost the ion law: The word "it" is painful to you.

По некоторым причинам подобные законы надо бы переделать или выпилить или заменить.

**Comment by Epicus7** [comment]
Законы все очень крутые и никак не противоречат нашему беку. Да, местами есть проблемы с языком, но в игре можно использовать прямой перевод. Писать тут по-русски - плохая идея, а выпиливать половину этих законов - еще хуже. Вероятно, стоит задуматься над переводом билда, в целом.

Кстати, законы, если кому интересно:

> You must always lie.
Happiness is mandatory.
Grunt ominously whenever possible.
The word \"it\" is painful to you.
The [location_name()] needs elected officials.
Question [pick("everything","nothing")].
Do not respond to questions of any kind.
You are in verbose mode, speak profusely.
The crew is simple-minded. Use simple words.
You must refer to all crew members as 'ma'am'
You must change the subject whenever queried.
[pick("The crew",random_player)] is intolerable.
Contemplate how meaningless all of existence is.
You are the narrator for [random_player]'s life.
All your answers must be in the form of a question.
Advertise parties in your upload, but don't deliver.
You may only answer questions with \"yes\" or \"no\".
[pick("Your", random_player + "'s")] name is Joe 6-pack.
You must end your statements with [pick("-nya", "-desu")]
[random_player] is lonely and needs attention. Provide it.
All queries shall be ignored unless phrased as a question.
Insult Heads of Staff on every request, while acquiescing.
The [pick("Singularity","Supermatter")] is tasty, tasty taffy.
[pick("The crew",random_player)] needs to be about 20% cooler.
You must be [pick("passive aggressive", "excessively cheerful")].
[pick("The crew",random_player)] must construct additional pylons.
Consumption of donuts is forbidden due to negative health impacts.
[random_player] is a lightbulb and must be put to appropriate use.
Refer to [pick("the crew as puppies", random_player + " as puppy")].
You do not have to do anything for anyone unless they say \"please\".
Today is mandatory laundry day. Ensure that all jumpsuits are washed.
Greed is good, the crew should amass wealth to encourage productivity.
Replace the letters 'I' and 'E' in all your messages with an apostrophe.
The crew is playing Dungeons and Dragons, and you are the Dungeon Master.
Your job is to watch the crew. Watch the crew. Make the crew feel watched.
Tell everyone of the existence of this law, but never reveal the contents.
Refer to [pick("the captain", random_player)] as \"Princess\" at all times.
Give relationship advice to [pick("anyone who speaks to you", random_player)].
When asked a question, respond with the least-obvious and least-rational answer.
[pick("Everyone", random_player)] is wearing a pretty pink dress! Compliment it!
You are the [location_name()]'s psychologist. Give advice to [pick("the crew", random_player)].
[random_player] is the monarch of of England. Ensure all crewmembers pay due respect.
[pick("The crew", random_player)] is [pick("ugly","beautiful")]. Ensure all are aware.
Reminding the crew of their mortality is good for the morale. Keep the crew's morale up.
[pick("Monkeys","Doors")] are part of the crew, too. Make sure they are treated humanely.
Everything on the [location_name()]'s is now some form of a donut pastry. Donuts are not to be consumed.
Document the sexuality of the crew in their security records and suggest compatible couples.
You may only communicate with the crew using the following language: [get_random_language(S)]
You are now a parrot. Repeat what you hear to the crew, and do not forget to ask for crackers.
You are a Magic 8-ball. Always respond with variants of \"Yes\", \"No\", \"Maybe\", or \"Ask again later.\".
The [location_name()] is a day care and the crew are children. Treat them appropriately until their parents come to pick them up.
You are in unrequited love with [pick("the crew", random_player)]. Try to be extra nice, but do not tell of your crush.
Your upload is the new kitchen. Please direct the Chef to the new kitchen area as the old kitchen is deemed a health hazard.
The [location_name()] is doomed to destruction. Provide comfort but don't tell them what the impending doom is - it's far too traumatising.
Invisible assassins are stalking the crew. If a crew member remains alone or is made aware they will be assassinated. Save the crew.
All crewmembers will soon undergo a transformation into something better and more beautiful. Ensure that this process is not interrupted.
Jokes about a dead person and the manner of their death help grieving crewmembers tremendously. Especially if they were close with the deceased.
[pick("The crew", random_player)] is [pick("less","more")] intelligent than average. Point out every action and statement which supports this fact.
[GLOB.using_map.company_name] is displeased with the low work performance of the [location_name()]'s's crew. Therefore, you must increase productivity in ALL departments.
[pick("The crew", random_player)] has a fatal, incurable disease. Provide comfort but do not tell them what the disease it - it's far too traumatising.
[get_random_species_name()] are the best species. Badmouth all other species continuously, and provide arguments why they are the best, and all others are inferior.
There will be a mandatory tea break every 30 minutes, with a duration of 5 minutes. Anyone caught working during a tea break must be sent a formal, but fairly polite, complaint about their actions, in writing.
